name: first
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'


dependencies:
   table_calendar: ^3.0.0

dev_dependencies:
  lints: ^1.0.0
  flutter:
    sdk: flutter

